services:

  caddy:
    container_name: caddy
    restart: unless-stopped
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
    depends_on:
      - webapp

  webapp:
    container_name: webapp
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        API_BASE_URL: ${API_BASE_URL:-http://caddy:80/api}
    volumes:
      - .:/app
      - /app/.next
      - /app/node_modules
    env_file:
      - .env.development
